monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - telegram

when@dev:
    monolog:
        handlers:
            # main:
            #     type: stream
            #     path: "%kernel.logs_dir%/%kernel.environment%.log"
            #     level: debug
            #     channels: ["!event"]
            # filter_for_errors:
            #     type: fingers_crossed
            #     # if *one* log is error or higher, pass *all* to file_log
            #     action_level: debug
            #     handler: telegram_api
            telegram_api:
                type: rotating_file
                path: "%kernel.logs_dir%/telegram_api/telegram_api.log"
                level: debug
                channels: ["telegram"]
                max_files: 50
                formatter: App\Formatter\ArrayFormatter
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
